jobs:
  build-and-test:
    docker:
      - image: 'eclipse-temurin:17-jdk'
    steps:
      - checkout
      - gradle/test
      - sonarcloud/scan

orbs:
  gradle: circleci/gradle@2.2.0
  sonarcloud: sonarsource/sonarcloud@1.0.3
version: 2.1
workflows:
  main:
    jobs:
      - build-and-test:
          context: SonarCloud